In [ ]:
from google.colab import files
uploaded = files.upload()

Saving CSE_Employability_Skill_Gap_50000_Realistic.xlsx to CSE_Employability_Skill_Gap_50000_Realistic.xlsx

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel(next(iter(uploaded)))

In [ ]:
df.head()

,Student_ID,Age,Gender,Degree,Specialization,Current_Year,Semester,CGPA,Attendance_Percentage,Internal_Marks,...,LeetCode_Problems_Solved,HackerRank_Badge_Level,Certifications,Hackathons_Attended,Resume_Score,Aptitude_Score,Technical_Interview_Score,HR_Interview_Score,Mock_Interview_Score,Skill_Gap_Level
0,CSE000001,24,Female,B.Tech,AI & ML,2,3,9.78,100,79,...,0,Gold,12,7,81,51,65,54,57,Medium
1,CSE000002,20,Female,B.Tech,Cyber Security,3,5,5.99,91,100,...,604,Gold,8,9,55,67,35,35,37,High
2,CSE000003,23,Female,B.Tech,Data Science,3,5,6.82,95,45,...,612,Silver,7,6,75,81,35,35,35,Medium
3,CSE000004,19,Other,B.Tech,Cloud Computing,3,6,8.93,77,69,...,783,Silver,6,6,69,82,46,40,45,High
4,CSE000005,23,Male,B.Tech,AI & ML,3,5,9.25,70,69,...,97,Bronze,2,10,83,96,59,52,57,Medium

Warning: Total number of columns (101) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Columns: 101 entries, Student_ID to Skill_Gap_Level
dtypes: float64(1), int64(94), object(6)
memory usage: 38.5+ MB

In [ ]:
df.describe()

,Age,Current_Year,Semester,CGPA,Attendance_Percentage,Internal_Marks,External_Marks,Mini_Project_Score,Major_Project_Score,Lab_Performance,...,Open_Source_Contributions,GitHub_Repositories,LeetCode_Problems_Solved,Certifications,Hackathons_Attended,Resume_Score,Aptitude_Score,Technical_Interview_Score,HR_Interview_Score,Mock_Interview_Score
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.00000,...,50000.000000,50000.00000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000
mean,20.998800,3.001600,5.503320,7.692029,79.976480,72.535200,70.02346,70.014620,69.810200,69.93170,...,9.972180,25.05868,398.81828,5.993800,4.999920,72.473900,70.144960,45.165900,45.48518,45.185380
std,1.997878,0.815408,1.708861,1.268385,11.833154,16.205834,17.57461,17.602136,17.604158,17.60132,...,6.072039,14.73087,230.69906,3.741748,3.165862,16.180072,17.583411,13.021166,13.58229,12.990859
min,18.000000,2.000000,3.000000,5.500000,60.000000,45.000000,40.00000,40.000000,40.000000,40.00000,...,0.000000,0.00000,0.00000,0.000000,0.000000,45.000000,40.000000,35.000000,35.00000,30.000000
25%,19.000000,2.000000,4.000000,6.590000,70.000000,58.000000,55.00000,55.000000,54.000000,55.00000,...,5.000000,12.00000,199.00000,3.000000,2.000000,58.000000,55.000000,35.000000,35.00000,35.000000
50%,21.000000,3.000000,5.000000,7.690000,80.000000,72.000000,70.00000,70.000000,70.000000,70.00000,...,10.000000,25.00000,399.00000,6.000000,5.000000,72.000000,70.000000,37.000000,37.00000,40.000000
75%,23.000000,4.000000,7.000000,8.790000,90.000000,87.000000,85.00000,85.000000,85.000000,85.00000,...,15.000000,38.00000,597.00000,9.000000,8.000000,87.000000,85.000000,55.000000,55.00000,54.000000
max,24.000000,4.000000,8.000000,9.900000,100.000000,100.000000,100.00000,100.000000,100.000000,100.00000,...,20.000000,50.00000,800.00000,12.000000,10.000000,100.000000,100.000000,91.000000,100.00000,90.000000

In [ ]:
df.isnull().sum()

Student_ID                   0
Age                          0
Gender                       0
Degree                       0
Specialization               0
                            ..
Aptitude_Score               0
Technical_Interview_Score    0
HR_Interview_Score           0
Mock_Interview_Score         0
Skill_Gap_Level              0
Length: 101, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

In [ ]:
X = df.drop("Skill_Gap_Level", axis=1)
y = df["Skill_Gap_Level"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9311

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.98      0.96      7416
           1       1.00      0.10      0.19       137
           2       0.87      0.84      0.86      2447

    accuracy                           0.93     10000
   macro avg       0.94      0.64      0.67     10000
weighted avg       0.93      0.93      0.93     10000

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[7239    0  177]
 [   0   14  123]
 [ 389    0 2058]]